---
- name: 'Add service account locally and generate keys'
  ansible.builtin.user:
    name: "{{ ssh_service_account_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: _user_results
...
