---
#=========================================================================
- name: 'Creating the docker registry container...'
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - common_vars.yml

  roles:
    - create-local-docker-registry
#=========================================================================



#=========================================================================
- name: 'Creating the testing environment...'
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - common_vars.yml

  roles:
    - create-testing-environment

  post_tasks:
    - name: 'Refresh Inventory'
      ansible.builtin.meta: refresh_inventory
#=========================================================================



#=========================================================================
- name: 'Adding a mySQL database container to the testing environment...'
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - common_vars.yml

  roles:
    - deploy-mysql-container
#=========================================================================



#=========================================================================
- name: 'Adding a nginx container to the testing environment...'
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - common_vars.yml

  environment:
    DB_HOST: "{{ _db_ip }}"
    DB_USERNAME: "{{ mysql_user }}"
    DB_PASSWORD: "{{ mysql_root_password }}"
    DB_NAME: "{{ mysql_database }}"

  roles:
    - deploy-nginx-container
#=========================================================================



#=========================================================================
- name: 'Deploying sample PHP application container...'
  hosts: all
  become: true
  gather_facts: true

  environment:
    DB_HOST: "{{ _db_ip }}"
    DB_USERNAME: "{{ mysql_user }}"
    DB_PASSWORD: "{{ mysql_root_password }}"
    DB_NAME: "{{ mysql_database }}"

  vars_files:
    - common_vars.yml

  roles:
    - deploy-php-container
#=========================================================================



#=========================================================================
# - name: 'Pulling code from repository'
#   hosts: localhost
#   connection: local
#   become: false
#   gather_facts: false

#   vars_files:
#     - common_vars.yml

#   roles:
#     - pull-code
#=========================================================================



#=========================================================================
# - name: 'Push new code to test'
#   hosts: localhost
#   connection: local
#   become: true
#   gather_facts: false

#   vars_files:
#     - common_vars.yml

#   roles:
#     - deploy-new-code
#=========================================================================
...
