---
- name: 'Login to docker hub'
  community.docker.docker_login:
    username: "{{ dockerhub_un }}"
    password: "{{ dockerhub_pw }}"

- name: 'Deploying nginx container'
  community.docker.docker_container:
    name: "{{ nginx_name }}"
    image: "{{ nginx_image }}"
    interactive: true
    published_ports:
      - "8080:{{ nginx_port }}"
    exposed_ports:
      - "8080:{{ nginx_port }}"
    tty: true
    privileged: true
    init: true
    state: started
    recreate: true
  register: _results

- name: 'Get the IP address of the new nginx container'
  ansible.builtin.set_fact:
    _nginx_ip:  "{{ _results | json_query(_query) }}"
  vars:
    _query: "container.NetworkSettings.IPAddress"

# - name: 'Add the IP to ansible inventory'
#   ansible.builtin.lineinfile:
#     path: inventory
#     line: "{{ _nginx_ip }}"
#     insertafter: EOF
...
